---
name: 'runic-action'
description: 'Run the Runic.jl code formatter on Julia files'
branding:
  icon: "book"
  color: "black"
inputs:
  version:
    description: 'Runic.jl version number or commit hash'
    default: "1"
runs:
  using: "composite"
  steps:
    - name: Check required dependencies
      shell: bash
      run: "${GITHUB_ACTION_PATH}/src/dependency-check.sh"
    - name: Install Runic
      shell: bash
      run: |
        julia --color=yes --project=@runic "${GITHUB_ACTION_PATH}/src/install.jl"
      env:
        INPUT_RUNIC_VERSION: ${{ inputs.version }}
    - name: Run Runic
      shell: bash
      run: |
        julia --color=yes --project=@runic "${GITHUB_ACTION_PATH}/src/check.jl"
